namespace Entites.StockFundamentals.FinancialsAsReported;

public class FinancialsAsReportedItem
{
    public string AccessionNumber { get; set; }
    public long? AccountsPayableCurrent { get; set; }
    public long? AccountsReceivableNetCurrent { get; set; }
    public long? AccruedIncomeTaxesNoncurrent { get; set; }
    public long? AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment { get; set; }
    public long? AccumulatedOtherComprehensiveIncomeLossNetOfTax { get; set; }
    public long? AllocatedShareBasedCompensationExpense { get; set; }
    public string AmendmentFlag { get; set; }
    public long? Assets { get; set; }
    public long? AssetsCurrent { get; set; }
    public long? AssetsNoncurrent { get; set; }
    public long? AuditorFirmId { get; set; }
    public string AuditorLocation { get; set; }
    public string AuditorName { get; set; }
    public long? AvailableForSaleSecuritiesDebtMaturitiesRollingAfterYearTenFairValue { get; set; }
    public long? AvailableForSaleSecuritiesDebtMaturitiesRollingYearSixThroughTenFairValue { get; set; }
    public long? AvailableForSaleSecuritiesDebtMaturitiesRollingYearTwoThroughFiveFairValue { get; set; }
    public long? AvailableForSaleSecuritiesDebtMaturitiesSingleMaturityDate { get; set; }
    public long? CashAndCashEquivalentsAtCarryingValue { get; set; }
    public long? CashCashEquivalentsAndMarketableSecurities { get; set; }
    public long? CashCashEquivalentsAndMarketableSecuritiesCost { get; set; }
    public long? CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents { get; set; }
    public long? CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect { get; set; }
    public long? CashEquivalentsAndMarketableSecuritiesAccumulatedGrossUnrealizedGainBeforeTax { get; set; }
    public long? CashEquivalentsAndMarketableSecuritiesAccumulatedGrossUnrealizedLossBeforeTax { get; set; }
    public string Cik { get; set; }
    public long? CityAreaCode { get; set; }
    public long? CommercialPaper { get; set; }
    public double? CommonStockDividendsPerShareDeclared { get; set; }
    public double? CommonStockParOrStatedValuePerShare { get; set; }
    public long? CommonStockSharesAuthorized { get; set; }
    public long? CommonStockSharesIssued { get; set; }
    public long? CommonStockSharesOutstanding { get; set; }
    public long? CommonStocksIncludingAdditionalPaidInCapital { get; set; }
    public long? ComprehensiveIncomeNetOfTax { get; set; }
    public long? ContractWithCustomerLiability { get; set; }
    public long? ContractWithCustomerLiabilityCurrent { get; set; }
    public long? ContractWithCustomerLiabilityRevenueRecognized { get; set; }
    public long? CostOfGoodsAndServicesSold { get; set; }
    public long? CurrentFederalTaxExpenseBenefit { get; set; }
    public string CurrentFiscalYearEndDate { get; set; }
    public long? CurrentForeignTaxExpenseBenefit { get; set; }
    public long? CurrentStateAndLocalTaxExpenseBenefit { get; set; }
    public long? dateFiled { get; set; }
    public long? DebtInstrumentCarryingAmount { get; set; }
    public long? DebtInstrumentUnamortizedDiscountPremiumAndDebtIssuanceCostsNet { get; set; }
    public long? DecreaseInUnrecognizedTaxBenefitsIsReasonablyPossible { get; set; }
    public long? DeferredFederalIncomeTaxExpenseBenefit { get; set; }
    public long? DeferredForeignIncomeTaxExpenseBenefit { get; set; }
    public long? DeferredIncomeTaxExpenseBenefit { get; set; }
    public long? DeferredIncomeTaxLiabilities { get; set; }
    public long? DeferredStateAndLocalIncomeTaxExpenseBenefit { get; set; }
    public long? DeferredTaxAssetsDeferredIncome { get; set; }
    public long? DeferredTaxAssetsGoodwillAndIntangibleAssets { get; set; }
    public long? DeferredTaxAssetsGross { get; set; }
    public long? DeferredTaxAssetsLeaseLiabilities { get; set; }
    public long? DeferredTaxAssetsLiabilitiesNet { get; set; }
    public long? DeferredTaxAssetsNet { get; set; }
    public long? DeferredTaxAssetsOther { get; set; }
    public long? DeferredTaxAssetsOtherComprehensiveLoss { get; set; }
    public long? DeferredTaxAssetsTaxCreditCarryforwards { get; set; }
    public long? DeferredTaxAssetsTaxCreditCarryforwardsForeign { get; set; }
    public long? DeferredTaxAssetsTaxCreditCarryforwardsResearch { get; set; }
    public long? DeferredTaxAssetsTaxDeferredExpenseReservesAndAccruals { get; set; }
    public long? DeferredTaxAssetsValuationAllowance { get; set; }
    public long? DeferredTaxLiabilitiesLeasingArrangements { get; set; }
    public long? DeferredTaxLiabilitiesMinimumTaxonForeignEarnings { get; set; }
    public long? DeferredTaxLiabilitiesOther { get; set; }
    public long? DeferredTaxLiabilitiesOtherComprehensiveIncome { get; set; }
    public long? Depreciation { get; set; }
    public long? DepreciationDepletionAndAmortization { get; set; }
    public long? DerivativeAssetsReductionForMasterNettingArrangementsIncludingTheEffectsOfCollateral { get; set; }
    public long? DerivativeFairValueOfDerivativeNet { get; set; }
    public long? DerivativeLiabilitiesReductionForMasterNettingArrangementsIncludingTheEffectsOfCollateral { get; set; }
    public string DocumentAnnualReport { get; set; }
    public string DocumentFiscalPeriodFocus { get; set; }
    public long? DocumentFiscalYearFocus { get; set; }
    public string DocumentPeriodEndDate { get; set; }
    public string DocumentTransitionReport { get; set; }
    public string documentType { get; set; }
    public double? EarningsPerShareBasic { get; set; }
    public double? EarningsPerShareDiluted { get; set; }
    public string EarningsPerSharePolicyTextBlock { get; set; }
    public double? EffectiveIncomeTaxRateContinuingOperations { get; set; }
    public double? EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate { get; set; }
    public long? EffectiveIncomeTaxRateReconciliationFdiiAmount { get; set; }
    public long? EffectiveIncomeTaxRateReconciliationShareBasedCompensationExcessTaxBenefitAmount { get; set; }
    public long? EffectiveIncomeTaxRateReconciliationTaxCutsAndJobsActOf2017Amount { get; set; }
    public long? EmployeeServiceShareBasedCompensationNonvestedAwardsTotalCompensationCostNotYetRecognized { get; set; }
    public string EmployeeServiceShareBasedCompensationNonvestedAwardsTotalCompensationCostNotYetRecognizedPeriodForRecognition1 { get; set; }
    public long? EmployeeServiceShareBasedCompensationTaxBenefitFromCompensationExpense { get; set; }
    public string EntityAddressAddressLine1 { get; set; }
    public string EntityAddressCityOrTown { get; set; }
    public long? EntityAddressPostalZipCode { get; set; }
    public string EntityAddressStateOrProvince { get; set; }
    public long? EntityCentralIndexKey { get; set; }
    public string EntityCurrentReportingStatus { get; set; }
    public string EntityEmergingGrowthCompany { get; set; }
    public string EntityFileNumber { get; set; }
    public string EntityFilerCategory { get; set; }
    public string EntityIncorporationStateCountryCode { get; set; }
    public string EntityInteractiveDataCurrent { get; set; }
    public string entityName { get; set; }
    public string EntityRegistrantName { get; set; }
    public string EntityShellCompany { get; set; }
    public string EntitySmallBusiness { get; set; }
    public string EntityTaxIdentificationNumber { get; set; }
    public string EntityVoluntaryFilers { get; set; }
    public string EntityWellKnownSeasonedIssuer { get; set; }
    public long? FederalIncomeTaxExpenseBenefitContinuingOperations { get; set; }
    public long? FinanceLeaseLiability { get; set; }
    public long? FinanceLeaseLiabilityCurrent { get; set; }
    public string FinanceLeaseLiabilityCurrentStatementOfFinancialPositionExtensibleList { get; set; }
    public long? FinanceLeaseLiabilityNoncurrent { get; set; }
    public string FinanceLeaseLiabilityNoncurrentStatementOfFinancialPositionExtensibleList { get; set; }
    public long? FinanceLeaseLiabilityPaymentsDue { get; set; }
    public long? FinanceLeaseLiabilityPaymentsDueAfterYearFive { get; set; }
    public long? FinanceLeaseLiabilityPaymentsDueNextTwelveMonths { get; set; }
    public long? FinanceLeaseLiabilityPaymentsDueYearFive { get; set; }
    public long? FinanceLeaseLiabilityPaymentsDueYearFour { get; set; }
    public long? FinanceLeaseLiabilityPaymentsDueYearThree { get; set; }
    public long? FinanceLeaseLiabilityPaymentsDueYearTwo { get; set; }
    public long? FinanceLeaseLiabilityUndiscountedExcessAmount { get; set; }
    public long? FinanceLeaseRightOfUseAsset { get; set; }
    public string FinanceLeaseRightOfUseAssetStatementOfFinancialPositionExtensibleList { get; set; }
    public long? ForeignIncomeTaxExpenseBenefitContinuingOperations { get; set; }
    public long? GrossProfit { get; set; }
    public long? HedgeAccountingAdjustmentsRelatedToLongTermDebt { get; set; }
    public string IcfrAuditorAttestationFlag { get; set; }
    public long? IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest { get; set; }
    public long? IncomeLossFromContinuingOperationsBeforeIncomeTaxesForeign { get; set; }
    public long? IncomeTaxesPaidNet { get; set; }
    public long? IncomeTaxExpenseBenefit { get; set; }
    public long? IncomeTaxReconciliationForeignIncomeTaxRateDifferential { get; set; }
    public long? IncomeTaxReconciliationIncomeTaxExpenseBenefitAtFederalStatutoryIncomeTaxRate { get; set; }
    public long? IncomeTaxReconciliationOtherAdjustments { get; set; }
    public long? IncomeTaxReconciliationStateAndLocalIncomeTaxes { get; set; }
    public long? IncomeTaxReconciliationTaxCreditsResearch { get; set; }
    public long? IncreaseDecreaseInAccountsPayable { get; set; }
    public long? IncreaseDecreaseInAccountsReceivable { get; set; }
    public long? IncreaseDecreaseInContractWithCustomerLiability { get; set; }
    public long? IncreaseDecreaseInInventories { get; set; }
    public long? IncreaseDecreaseInOtherOperatingAssets { get; set; }
    public long? IncreaseDecreaseInOtherOperatingLiabilities { get; set; }
    public long? IncreaseDecreaseInOtherReceivables { get; set; }
    public long? InterestCostsIncurred { get; set; }
    public long? InterestExpense { get; set; }
    public long? InterestPaidNet { get; set; }
    public long? InventoryNet { get; set; }
    public long? InvestmentIncomeInterestAndDividend { get; set; }
    public string irsNumber { get; set; }
    public long? LesseeOperatingAndFinanceLeaseLeaseNotYetCommencedPaymentsDue { get; set; }
    public long? LesseeOperatingandFinanceLeaseLiabilityPaymentsDue { get; set; }
    public long? LesseeOperatingAndFinanceLeaseLiabilityToBePaidAfterYearFive { get; set; }
    public long? LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearFive { get; set; }
    public long? LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearFour { get; set; }
    public long? LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearOne { get; set; }
    public long? LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearThree { get; set; }
    public long? LesseeOperatingAndFinanceLeaseLiabilityToBePaidYearTwo { get; set; }
    public long? LesseeOperatingandFinanceLeaseLiabilityUndiscountedExcessAmount { get; set; }
    public string LesseeOperatingandFinanceLeaseTermofContract { get; set; }
    public long? LesseeOperatingLeaseLiabilityPaymentsDue { get; set; }
    public long? LesseeOperatingLeaseLiabilityPaymentsDueAfterYearFive { get; set; }
    public long? LesseeOperatingLeaseLiabilityPaymentsDueNextTwelveMonths { get; set; }
    public long? LesseeOperatingLeaseLiabilityPaymentsDueYearFive { get; set; }
    public long? LesseeOperatingLeaseLiabilityPaymentsDueYearFour { get; set; }
    public long? LesseeOperatingLeaseLiabilityPaymentsDueYearThree { get; set; }
    public long? LesseeOperatingLeaseLiabilityPaymentsDueYearTwo { get; set; }
    public long? LesseeOperatingLeaseLiabilityUndiscountedExcessAmount { get; set; }
    public long? Liabilities { get; set; }
    public long? LiabilitiesAndStockholdersEquity { get; set; }
    public long? LiabilitiesCurrent { get; set; }
    public long? LiabilitiesNoncurrent { get; set; }
    public string LocalPhoneNumber { get; set; }
    public long? LongTermDebtCurrent { get; set; }
    public long? LongTermDebtMaturitiesRepaymentsOfPrincipalAfterYearFive { get; set; }
    public long? LongTermDebtMaturitiesRepaymentsOfPrincipalInNextTwelveMonths { get; set; }
    public long? LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFive { get; set; }
    public long? LongTermDebtMaturitiesRepaymentsOfPrincipalInYearFour { get; set; }
    public long? LongTermDebtMaturitiesRepaymentsOfPrincipalInYearThree { get; set; }
    public long? LongTermDebtMaturitiesRepaymentsOfPrincipalInYearTwo { get; set; }
    public long? LongTermDebtNoncurrent { get; set; }
    public long? MarketableSecuritiesCurrent { get; set; }
    public long? MarketableSecuritiesNoncurrent { get; set; }
    public long? NetCashProvidedByUsedInFinancingActivities { get; set; }
    public long? NetCashProvidedByUsedInInvestingActivities { get; set; }
    public long? NetCashProvidedByUsedInOperatingActivities { get; set; }
    public long? NetIncomeLoss { get; set; }
    public long? NoncurrentAssets { get; set; }
    public long? NonoperatingIncomeExpense { get; set; }
    public long? NontradeReceivablesCurrent { get; set; }
    public long? OperatingandFinanceLeaseLiability { get; set; }
    public long? OperatingandFinanceLeaseRightofUseAsset { get; set; }
    public double? OperatingandFinanceLeaseWeightedAverageDiscountRatePercent { get; set; }
    public string OperatingandFinanceLeaseWeightedAverageRemainingLeaseTerm { get; set; }
    public long? OperatingExpenses { get; set; }
    public long? OperatingIncomeLoss { get; set; }
    public long? OperatingLeaseCost { get; set; }
    public long? OperatingLeaseLiability { get; set; }
    public long? OperatingLeaseLiabilityCurrent { get; set; }
    public string OperatingLeaseLiabilityCurrentStatementOfFinancialPositionExtensibleList { get; set; }
    public long? OperatingLeaseLiabilityNoncurrent { get; set; }
    public string OperatingLeaseLiabilityNoncurrentStatementOfFinancialPositionExtensibleList { get; set; }
    public long? OperatingLeasePayments { get; set; }
    public long? OperatingLeaseRightOfUseAsset { get; set; }
    public string OperatingLeaseRightOfUseAssetStatementOfFinancialPositionExtensibleList { get; set; }
    public long? OtherAccruedLiabilitiesNoncurrent { get; set; }
    public long? OtherAssetsCurrent { get; set; }
    public long? OtherAssetsNoncurrent { get; set; }
    public long? OtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax { get; set; }
    public long? OtherComprehensiveIncomeLossDerivativeInstrumentGainLossafterReclassificationandTax { get; set; }
    public long? OtherComprehensiveIncomeLossDerivativeInstrumentGainLossbeforeReclassificationafterTax { get; set; }
    public long? OtherComprehensiveIncomeLossDerivativeInstrumentGainLossReclassificationAfterTax { get; set; }
    public long? OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationAdjustmentNetOfTax { get; set; }
    public long? OtherComprehensiveIncomeLossNetOfTaxPortionAttributableToParent { get; set; }
    public long? OtherComprehensiveIncomeLossReclassificationAdjustmentFromAOCIForSaleOfSecuritiesNetOfTax { get; set; }
    public long? OtherComprehensiveIncomeUnrealizedHoldingGainLossOnSecuritiesArisingDuringPeriodNetOfTax { get; set; }
    public long? OtherLiabilitiesCurrent { get; set; }
    public long? OtherLiabilitiesNoncurrent { get; set; }
    public long? OtherNoncashIncomeExpense { get; set; }
    public long? OtherNonoperatingIncomeExpense { get; set; }
    public long? PaymentsForProceedsFromOtherInvestingActivities { get; set; }
    public long? PaymentsForRepurchaseOfCommonStock { get; set; }
    public long? PaymentsOfDividends { get; set; }
    public long? PaymentsRelatedToTaxWithholdingForShareBasedCompensation { get; set; }
    public long? PaymentsToAcquireAvailableForSaleSecuritiesDebt { get; set; }
    public long? PaymentsToAcquireBusinessesNetOfCashAcquired { get; set; }
    public long? PaymentsToAcquirePropertyPlantAndEquipment { get; set; }
    public long? PerformanceObligationsinArrangements { get; set; }
    public long? periodEnd { get; set; }
    public long? periodStart { get; set; }
    public long? ProceedsFromIssuanceOfLongTermDebt { get; set; }
    public long? ProceedsFromMaturitiesPrepaymentsAndCallsOfAvailableForSaleSecurities { get; set; }
    public long? ProceedsFromPaymentsForOtherFinancingActivities { get; set; }
    public long? ProceedsFromRepaymentsOfCommercialPaper { get; set; }
    public long? ProceedsFromRepaymentsOfShortTermDebtMaturingInMoreThanThreeMonths { get; set; }
    public long? ProceedsFromRepaymentsOfShortTermDebtMaturingInThreeMonthsOrLess { get; set; }
    public long? ProceedsFromSaleOfAvailableForSaleSecuritiesDebt { get; set; }
    public long? ProceedsFromShortTermDebtMaturingInMoreThanThreeMonths { get; set; }
    public long? PropertyPlantAndEquipmentGross { get; set; }
    public long? PropertyPlantAndEquipmentNet { get; set; }
    public long? RepaymentsOfLongTermDebt { get; set; }
    public long? RepaymentsOfShortTermDebtMaturingInMoreThanThreeMonths { get; set; }
    public string reportLink { get; set; }
    public long? ResearchAndDevelopmentExpense { get; set; }
    public long? RestrictedInvestments { get; set; }
    public long? RetainedEarningsAccumulatedDeficit { get; set; }
    public long? RevenueFromContractWithCustomerExcludingAssessedTax { get; set; }
    public long? RightofUseAssetsObtainedinExchangeforOperatingandFinanceLeaseLiabilities { get; set; }
    public long? SellingGeneralAndAdministrativeExpense { get; set; }
    public long? ShareBasedCompensation { get; set; }
    public long? StateAndLocalIncomeTaxExpenseBenefitContinuingOperations { get; set; }
    public long? StockholdersEquity { get; set; }
    public long? StockRepurchasedAndRetiredDuringPeriodShares { get; set; }
    public long? StockRepurchasedAndRetiredDuringPeriodValue { get; set; }
    public string TradingSymbol { get; set; }
    public long? UnrecognizedTaxBenefits { get; set; }
    public long? UnrecognizedTaxBenefitsDecreasesResultingFromPriorPeriodTaxPositions { get; set; }
    public long? UnrecognizedTaxBenefitsDecreasesResultingFromSettlementsWithTaxingAuthorities { get; set; }
    public long? UnrecognizedTaxBenefitsIncreasesResultingFromCurrentPeriodTaxPositions { get; set; }
    public long? UnrecognizedTaxBenefitsIncreasesResultingFromPriorPeriodTaxPositions { get; set; }
    public long? UnrecognizedTaxBenefitsReductionsResultingFromLapseOfApplicableStatuteOfLimitations { get; set; }
    public long? UnrecognizedTaxBenefitsThatWouldImpactEffectiveTaxRate { get; set; }
    public long? UnrecordedUnconditionalPurchaseObligationBalanceOnFifthAnniversary { get; set; }
    public long? UnrecordedUnconditionalPurchaseObligationBalanceOnFirstAnniversary { get; set; }
    public long? UnrecordedUnconditionalPurchaseObligationBalanceOnFourthAnniversary { get; set; }
    public long? UnrecordedUnconditionalPurchaseObligationBalanceOnSecondAnniversary { get; set; }
    public long? UnrecordedUnconditionalPurchaseObligationBalanceOnThirdAnniversary { get; set; }
    public long? UnrecordedUnconditionalPurchaseObligationBalanceSheetAmount { get; set; }
    public long? UnrecordedUnconditionalPurchaseObligationDueAfterFiveYears { get; set; }
    public string update { get; set; }
    public long? VariableLeaseCost { get; set; }
    public long? WeightedAverageNumberDilutedSharesOutstandingAdjustment { get; set; }
    public long? WeightedAverageNumberOfDilutedSharesOutstanding { get; set; }
    public long? WeightedAverageNumberOfSharesOutstandingBasic { get; set; }
    public string Id { get; set; }
    public string Key { get; set; }
    public string Subkey { get; set; }
    public long Date { get; set; }
    public double? updated { get; set; }
}
